### ISSUE TITLE
404.  Really?

### ISSUE THREAD

**Issue by eswright** [ElectionGuard/ElectionGuard-SDK-C-Documentation#2]
Doesn’t Microsoft have the capability to run scripts to prevent things like this from happening?

> View this documentation at https://github.com/ElectionGuard/ElectionGuard-SDK-C-Documentation/blob/master
>

**Comment by ElectionGuard** [comment]
Thanks for bringing this to our attention. Fixed in PR #3

**Comment by eswright** [comment]
It would be cool if something could be running on all of GitHub to alert authors of link status issues.  Thanks.
